version: "2.4"

volumes:
  blockchain:
    name: btc-data
  memmpool_api:
    name: btc-api
  memmpool_indexer:
    name: btc-db
  mempool_blockchain:
    name: mempool-blockchain
  electrs_data:
    name: electrs-data

services:
  node:
    container_name: btc-node
    image: eugenenostrdev/bitcoin_signet:amd64
    mem_limit: 2048m
    cpus: 0.8
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-rpcuser=rpcuser", "-rpcpassword=rpcpassword", "-rpcport=38332", "getblockchaininfo"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    restart: unless-stopped
    stop_grace_period: 15m
    volumes:
      - blockchain:/root/.bitcoin
    environment:
      UACOMMENT: $UACOMMENT
      BLOCKPRODUCTIONDELAY: ${BLOCKPRODUCTIONDELAY:-30}
      MINERENABLED: ${MINERENABLED:-0} # change this to 1 if this node needs to mine (however for simplicity there should only be one mining node per challenge)
      NBITS: $NBITS
      MINETO: ${MINETO:-tb1qk4pq0rh75qtph47wlufhyss43flhvhvwe4zt8a}
      PRIVKEY: ${PRIVKEY:-cRz3Ci2aUNmdP4pViSM8LafwKHZmvn4X6gjeCXzVkBYBLhzA3uFC} # private key path is m/84'/1'/0'/0/0 of test wallet mnemonic "margin radio diamond leg loud street announce guitar video shiver speed eyebrow"
      SIGNETCHALLENGE: ${SIGNETCHALLENGE:-512102b57c4413a0354bcc360a37e035f26670deda14bab613c28fbd30fe52b2deccc151ae}
      EXTERNAL_IP: $EXTERNAL_IP
      ADDNODE: ${ADDNODE:-207.180.254.78}
      RPCUSER: ${RPCUSER:-rpcuser}
      RPCPASSWORD: ${RPCPASSWORD:-rpcpassword}
    ports:
      - 18333:18333 # Make this a public node.
      - 8333:8333 # Make this a public node.
      - 38333:38333 # Make this a public node.
      - 38332:38332
    networks:
      - mempoolnetwork

  mempool_api:
    container_name: mempool-api
    image: eugenenostrdev/mempool-api:amd64-1.1.7
    environment:
      MEMPOOL_BACKEND: "esplora"
      ESPLORA_REST_API_URL: "http://mempool-electrs:3003"
      ELECTRUM_HOST: "mempool-electrs"
      ELECTRUM_PORT: "5001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: "node"
      CORE_RPC_PORT: "38332"
      CORE_RPC_USERNAME: "rpcuser"
      CORE_RPC_PASSWORD: "rpcpassword"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: "debug"
      MEMPOOL_INDEXING_BLOCKS_AMOUNT: -1
      VIRTUAL_HOST: indexer.angor.io
      VIRTUAL_PORT: 8999
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: indexer.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:8999
    restart: unless-stopped
    stop_grace_period: 1m
    command: "./wait-for-it.sh mempool_db:3306 --timeout=720 --strict -- ./start.sh"
    ports:
      - 8999:8999
    volumes:
      - memmpool_api:/backend/cache
    networks:
      - mempoolnetwork
      - proxy

  mempool_db:
    container_name: mempool-db
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.21
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - memmpool_indexer:/var/lib/mysql
    networks:
      - mempoolnetwork

  mempool_web:
    container_name: "mempool_web"
    environment:
      MAINNET_ENABLED: "false"
      ROOT_NETWORK: "signet"
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool_api"
      LIGHTNING: "false"
      VIRTUAL_HOST: explorer.angor.io
      VIRTUAL_PORT: 8080
      VIRTUAL_PROTO: http
      VIRTUAL_NETWORK: proxy
      LETSENCRYPT_HOST: explorer.angor.io
      LETSENCRYPT_EMAIL: admin@blockcore.net
      ASPNETCORE_URLS: http://+:8080
    image: mempool/frontend:latest
    user: "0:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for mempool_db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - "8080:8080"
    networks:
      - mempoolnetwork
      - proxy

  mempool_electrs:
    container_name: mempool-electrs
    image: eugenenostrdev/electrs-app:amd64-1.1
    ports:
      - 5001:5001
      - 3003:3003
    depends_on:
      node:
        condition: service_healthy
    entrypoint:
      /bin/electrs
    command: |
      --network signet
      --jsonrpc-import
      --daemon-rpc-addr btc-node:38332
      --cookie "rpcuser:rpcpassword"
      --db-dir /electrs
      --http-addr 0.0.0.0:3003
      --electrum-rpc-addr 0.0.0.0:5001
      -vvvv
    volumes:
      - electrs_data:/electrs
    networks:
      - mempoolnetwork

networks:
  mempoolnetwork:
    external: false
    name: mempoolnetwork
  proxy:
    external: true
    name: proxy
