name: Docker build on tag

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

permissions:
  contents: read

jobs:
  build-self-hosted:
    strategy:
      matrix:
        service:
          - frontend
          - backend
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: self-hosted
      service: ${{ matrix.service }}
    secrets:
      DOCKER_KEY: ${{ secrets.DOCKER_KEY }}

  build-github-hosted:
    strategy:
      matrix:
        service:
          - frontend
          - backend
    uses: ./.github/workflows/reusable-build.yml
    with:
      runner: ubuntu-latest
      service: ${{ matrix.service }}
    secrets:
      DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
